tests: update gpu weekly test to test mis hip instead of fw hip (#1780)
I am moving this test because the fw tests fails on runners due to the
following error

```
File "/__w/gem5/gem5/tests/../ext/testlib/helper.py", line 207, in log_call
    raise subprocess.CalledProcessError(retval, cmdstr)
subprocess.CalledProcessError: Command '/__w/gem5/gem5/build/VEGA_X86/gem5.opt -d /tmp/gem5outesz2d05s -re --silent-redirect /__w/gem5/gem5/configs/example/apu_se.py -n3 --mem-size=8GB -c /__w/gem5/gem5/tests/gem5/gpu/../resources/gpu-pannotia/pannotia-bins/fw_hip.gem5 --options -f /__w/gem5/gem5/tests/gem5/gpu/../resources/gpu-pannotia/pannotia-datasets/1k_128k.gr -m default' died with &lt;Signals.SIGKILL: 9&gt;.
```

This looks like runners are killing the test due to lack of resources.
This test did past locally so I changed the test with mis_hip.